name: CD
on: 
  push:
    branches: 
      - development
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install
    - run: npx nx build terminology-api

  publish:
    needs: [build]
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@master
    - name: Publish to hub.docker.com/kuunika
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: kuunika/kuunika
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
